/**
 * @Category React Hook function
 * Provide single source to manage application static menus items
 * 
**/

import { $t } from 'hooks/i18n';

export default function useMenus() {
    
    
    return {
	navbarTopRight: [
  {
    "to": "/applogs",
    "label": $t('logs'),
    "icon": "pi pi-book",
    "iconcolor": "",
    "target": "",
  },
  {
    "to": "/encaissementexterne",
    "label": $t('encaissementExterne'),
    "icon": "pi pi-th-large",
    "iconcolor": "",
    "target": "",
  }
],
	navbarTopLeft: [
  {
    "to": "/usersnode",
    "label": $t('utilisateurs'),
    "icon": "pi pi-users",
    "iconcolor": "",
    "target": "",
  },
  {
    "to": "/roles",
    "label": $t('rles'),
    "icon": "pi pi-user-edit",
    "iconcolor": "",
    "target": "",
  },
  {
    "to": "/permissionsnode",
    "label": $t('permissions'),
    "icon": "pi pi-lock",
    "iconcolor": "",
    "target": "",
  },
  {
    "to": "/encaissementexterne",
    "label": $t('encaissementExterne'),
    "icon": "pi pi-th-large",
    "iconcolor": "",
    "target": "",
  }
],
	navbarSideLeft: [
  {
    "to": "/home",
    "label": $t('home'),
    "icon": "pi pi-home",
    "iconcolor": "",
    "target": "",
  },
  {
    "to": "/listmenus/personnel",
    "label": $t('personnel'),
    "icon": "pi pi-user",
    "iconcolor": "",
    "target": "_blank",
    "items": [
      {
        "to": "/proprietaire",
        "label": "Propriétaires",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/responsable",
        "label": "Responsables",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      }
    ]
  },
  {
    "to": "/listmenus/patrimoine",
    "label": $t('patrimoine'),
    "icon": "pi pi-building",
    "iconcolor": "",
    "target": "_blank",
    "items": [
      {
        "to": "/residence",
        "label": "Residence",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/batiment",
        "label": "Batiment",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/pavillon",
        "label": "Pavillon",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/etage",
        "label": "Etages",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/couloir",
        "label": "Couloir",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/chambre",
        "label": "Chambre",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/unitelocation",
        "label": "Unite Location",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/familleunite",
        "label": "Famille Unités de Location",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/equipement",
        "label": "Equipements",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/familleequipement",
        "label": "Famille Equipements",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      }
    ]
  },
  {
    "to": "/listmenus/clients",
    "label": $t('clients'),
    "icon": "pi pi-user",
    "iconcolor": "",
    "target": "",
    "items": [
      {
        "to": "/client",
        "label": "Etudiants",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/garant",
        "label": "Garants",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/garantie",
        "label": "Garanties",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      }
    ]
  },
  {
    "to": "/listmenus/dossierslocation",
    "label": $t('dossiersDeLocation'),
    "icon": "pi pi-folder",
    "iconcolor": "",
    "target": "",
    "items": [
      {
        "to": "/dossierlocation",
        "label": "Gestion Dossiers",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/contrat",
        "label": "Gestion Contrats",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/facturation",
        "label": "Facturations",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/facture",
        "label": "Factures",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/lignesfacture",
        "label": "Lignes Facture",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/encaissement",
        "label": "Encaissements",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/encaissement",
        "label": "Remboursements",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/tarification",
        "label": "Tarifications",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/basetarification",
        "label": "Base Tarification",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      }
    ]
  },
  {
    "to": "/listmenus/gestionreclamations",
    "label": $t('gestionDesRclamations'),
    "icon": "pi pi-exclamation-triangle",
    "iconcolor": "",
    "target": "",
    "items": [
      {
        "to": "/reclamation",
        "label": "Suivi",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/reclamation",
        "label": "Traitement",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/reclamation",
        "label": "Resolution",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      }
    ]
  },
  {
    "to": "/listmenus/demandeslogement",
    "label": $t('demandesDeLogement'),
    "icon": "pi pi-copy",
    "iconcolor": "",
    "target": "",
    "items": [
      {
        "to": "/demandelogement",
        "label": "Soumises",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/demandelogement",
        "label": "En Attente",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/",
        "label": "Validés",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/",
        "label": "Clients effectifs",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/",
        "label": "Rejetés",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/demandelogement/vuedemande",
        "label": "Menu 6",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      }
    ]
  },
  {
    "to": "/listmenus/espaceclient",
    "label": $t('espaceClient'),
    "icon": "pi pi-user",
    "iconcolor": "",
    "target": "",
    "items": [
      {
        "to": "/lecturedesindex",
        "label": "Index Eau & Electricité",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/reclamation",
        "label": "Réclamation",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      }
    ]
  },
  {
    "to": "/listmenus/gestioncompteurs",
    "label": $t('gestionDesCompteurs'),
    "icon": "pi pi-bolt",
    "iconcolor": "",
    "target": "",
    "items": [
      {
        "to": "/lecturedesindex",
        "label": "Index Eau & Electricité",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      },
      {
        "to": "/lecturedesindex",
        "label": "Dépassements",
        "icon": "pi pi-th-large",
        "iconcolor": "",
        "target": "",
      }
    ]
  },
  {
    "to": "/demandelogement/follow",
    "label": $t('suiviDemandeDeLogement'),
    "icon": "pi pi-undo",
    "iconcolor": "",
    "target": "",
  },
  {
    "to": "/encaissementexterne",
    "label": $t('encaissementExterne'),
    "icon": "pi pi-th-large",
    "iconcolor": "",
    "target": "",
  },
  {
    "to": "/encaissement/fraisreservation",
    "label": $t('fraisreservation'),
    "icon": "pi pi-th-large",
    "iconcolor": "",
    "target": "",
  },
  {
    "to": "/encaissementdetails",
    "label": $t('encaissementdetails'),
    "icon": "pi pi-th-large",
    "iconcolor": "",
    "target": "",
  }
],
	periodicite: [    
{value: "Journalière", label: $t('journalire')},
	{value: "Hebdomadaire", label: $t('hebdomadaire')},
	{value: "Mensuelle", label: $t('mensuelle')},
	{value: "Trimestrielle", label: $t('trimestrielle')},
	{value: "Semestrielle", label: $t('semestrielle')},
	{value: "Annuelle", label: $t('annuelle')}
    ],
	situationFamiliale: [    
{value: "Célibataire", label: $t('clibataire')},
	{value: "Marié", label: $t('mari')},
	{value: "Autres", label: $t('autres')}
    ],
	paysClient: [    
{value: "Afghanistan", label: $t('afghanistan')},
	{value: "Aland Islands", label: $t('alandIslands')},
	{value: "Albania", label: $t('albania')},
	{value: "Algeria", label: $t('algeria')},
	{value: "American Samoa", label: $t('americanSamoa')},
	{value: "AndorrA", label: $t('andorra')},
	{value: "Angola", label: $t('angola')},
	{value: "Anguilla", label: $t('anguilla')},
	{value: "Antarctica", label: $t('antarctica')},
	{value: "Antigua and Barbuda", label: $t('antiguaAndBarbuda')},
	{value: "Argentina", label: $t('argentina')},
	{value: "Armenia", label: $t('armenia')},
	{value: "Aruba", label: $t('aruba')},
	{value: "Australia", label: $t('australia')},
	{value: "Austria", label: $t('austria')},
	{value: "Azerbaijan", label: $t('azerbaijan')},
	{value: "Bahamas", label: $t('bahamas')},
	{value: "Bahrain", label: $t('bahrain')},
	{value: "Bangladesh", label: $t('bangladesh')},
	{value: "Barbados", label: $t('barbados')},
	{value: "Belarus", label: $t('belarus')},
	{value: "Belgium", label: $t('belgium')},
	{value: "Belize", label: $t('belize')},
	{value: "Benin", label: $t('benin')},
	{value: "Bermuda", label: $t('bermuda')},
	{value: "Bhutan", label: $t('bhutan')},
	{value: "Bolivia", label: $t('bolivia')},
	{value: "Bosnia and Herzegovina", label: $t('bosniaAndHerzegovina')},
	{value: "Botswana", label: $t('botswana')},
	{value: "Bouvet Island", label: $t('bouvetIsland')},
	{value: "Brazil", label: $t('brazil')},
	{value: "British Indian Ocean Territory", label: $t('britishIndianOceanTerritory')},
	{value: "Brunei Darussalam", label: $t('bruneiDarussalam')},
	{value: "Bulgaria", label: $t('bulgaria')},
	{value: "Burkina Faso", label: $t('burkinaFaso')},
	{value: "Burundi", label: $t('burundi')},
	{value: "Cambodia", label: $t('cambodia')},
	{value: "Cameroon", label: $t('cameroon')},
	{value: "Canada", label: $t('canada')},
	{value: "Cape Verde", label: $t('capeVerde')},
	{value: "Cayman Islands", label: $t('caymanIslands')},
	{value: "Central African Republic", label: $t('centralAfricanRepublic')},
	{value: "Chad", label: $t('chad')},
	{value: "Chile", label: $t('chile')},
	{value: "China", label: $t('china')},
	{value: "Christmas Island", label: $t('christmasIsland')},
	{value: "Cocos (Keeling) Islands", label: $t('cocosKeelingIslands')},
	{value: "Colombia", label: $t('colombia')},
	{value: "Comoros", label: $t('comoros')},
	{value: "Congo", label: $t('congo')},
	{value: "Cook Islands", label: $t('cookIslands')},
	{value: "Costa Rica", label: $t('costaRica')},
	{value: "Cote D'Ivoire", label: $t('coteDivoire')},
	{value: "Croatia", label: $t('croatia')},
	{value: "Cuba", label: $t('cuba')},
	{value: "Cyprus", label: $t('cyprus')},
	{value: "Czech Republic", label: $t('czechRepublic')},
	{value: "Denmark", label: $t('denmark')},
	{value: "Djibouti", label: $t('djibouti')},
	{value: "Dominica", label: $t('dominica')},
	{value: "Dominican Republic", label: $t('dominicanRepublic')},
	{value: "Ecuador", label: $t('ecuador')},
	{value: "Egypt", label: $t('egypt')},
	{value: "El Salvador", label: $t('elSalvador')},
	{value: "Equatorial Guinea", label: $t('equatorialGuinea')},
	{value: "Eritrea", label: $t('eritrea')},
	{value: "Estonia", label: $t('estonia')},
	{value: "Ethiopia", label: $t('ethiopia')},
	{value: "Falkland Islands (Malvinas)", label: $t('falklandIslandsMalvinas')},
	{value: "Faroe Islands", label: $t('faroeIslands')},
	{value: "Fiji", label: $t('fiji')},
	{value: "Finland", label: $t('finland')},
	{value: "France", label: $t('france')},
	{value: "French Guiana", label: $t('frenchGuiana')},
	{value: "French Polynesia", label: $t('frenchPolynesia')},
	{value: "French Southern Territories", label: $t('frenchSouthernTerritories')},
	{value: "Gabon", label: $t('gabon')},
	{value: "Gambia", label: $t('gambia')},
	{value: "Georgia", label: $t('georgia')},
	{value: "Germany", label: $t('germany')},
	{value: "Ghana", label: $t('ghana')},
	{value: "Gibraltar", label: $t('gibraltar')},
	{value: "Greece", label: $t('greece')},
	{value: "Greenland", label: $t('greenland')},
	{value: "Grenada", label: $t('grenada')},
	{value: "Guadeloupe", label: $t('guadeloupe')},
	{value: "Guam", label: $t('guam')},
	{value: "Guatemala", label: $t('guatemala')},
	{value: "Guernsey", label: $t('guernsey')},
	{value: "Guinea", label: $t('guinea')},
	{value: "Guinea-Bissau", label: $t('guineaBissau')},
	{value: "Guyana", label: $t('guyana')},
	{value: "Haiti", label: $t('haiti')},
	{value: "Heard Island and Mcdonald Islands", label: $t('heardIslandAndMcdonaldIslands')},
	{value: "Holy See (Vatican City State)", label: $t('holySeeVaticanCityState')},
	{value: "Honduras", label: $t('honduras')},
	{value: "Hong Kong", label: $t('hongKong')},
	{value: "Hungary", label: $t('hungary')},
	{value: "Iceland", label: $t('iceland')},
	{value: "India", label: $t('india')},
	{value: "Indonesia", label: $t('indonesia')},
	{value: "Iran", label: $t('iran')},
	{value: "Iraq", label: $t('iraq')},
	{value: "Ireland", label: $t('ireland')},
	{value: "Isle of Man", label: $t('isleOfMan')},
	{value: "Israel", label: $t('israel')},
	{value: "Italy", label: $t('italy')},
	{value: "Jamaica", label: $t('jamaica')},
	{value: "Japan", label: $t('japan')},
	{value: "Jersey", label: $t('jersey')},
	{value: "Jordan", label: $t('jordan')},
	{value: "Kazakhstan", label: $t('kazakhstan')},
	{value: "Kenya", label: $t('kenya')},
	{value: "Kiribati", label: $t('kiribati')},
	{value: "Korea", label: $t('korea')},
	{value: "Kuwait", label: $t('kuwait')},
	{value: "Kyrgyzstan", label: $t('kyrgyzstan')},
	{value: "Lao People's Democratic Republic", label: $t('laoPeoplesDemocraticRepublic')},
	{value: "Latvia", label: $t('latvia')},
	{value: "Lebanon", label: $t('lebanon')},
	{value: "Lesotho", label: $t('lesotho')},
	{value: "Liberia", label: $t('liberia')},
	{value: "Libyan Arab Jamahiriya", label: $t('libyanArabJamahiriya')},
	{value: "Liechtenstein", label: $t('liechtenstein')},
	{value: "Lithuania", label: $t('lithuania')},
	{value: "Luxembourg", label: $t('luxembourg')},
	{value: "Macao", label: $t('macao')},
	{value: "Macedonia", label: $t('macedonia')},
	{value: "Madagascar", label: $t('madagascar')},
	{value: "Malawi", label: $t('malawi')},
	{value: "Malaysia", label: $t('malaysia')},
	{value: "Maldives", label: $t('maldives')},
	{value: "Mali", label: $t('mali')},
	{value: "Malta", label: $t('malta')},
	{value: "Marshall Islands", label: $t('marshallIslands')},
	{value: "Martinique", label: $t('martinique')},
	{value: "Mauritania", label: $t('mauritania')},
	{value: "Mauritius", label: $t('mauritius')},
	{value: "Mayotte", label: $t('mayotte')},
	{value: "Mexico", label: $t('mexico')},
	{value: "Micronesia", label: $t('micronesia')},
	{value: "Moldova", label: $t('moldova')},
	{value: "Monaco", label: $t('monaco')},
	{value: "Mongolia", label: $t('mongolia')},
	{value: "Montserrat", label: $t('montserrat')},
	{value: "Morocco", label: $t('morocco')},
	{value: "Mozambique", label: $t('mozambique')},
	{value: "Myanmar", label: $t('myanmar')},
	{value: "Namibia", label: $t('namibia')},
	{value: "Nauru", label: $t('nauru')},
	{value: "Nepal", label: $t('nepal')},
	{value: "Netherlands", label: $t('netherlands')},
	{value: "Netherlands Antilles", label: $t('netherlandsAntilles')},
	{value: "New Caledonia", label: $t('newCaledonia')},
	{value: "New Zealand", label: $t('newZealand')},
	{value: "Nicaragua", label: $t('nicaragua')},
	{value: "Niger", label: $t('niger')},
	{value: "Nigeria", label: $t('nigeria')},
	{value: "Niue", label: $t('niue')},
	{value: "Norfolk Island", label: $t('norfolkIsland')},
	{value: "Northern Mariana Islands", label: $t('northernMarianaIslands')},
	{value: "Norway", label: $t('norway')},
	{value: "Oman", label: $t('oman')},
	{value: "Pakistan", label: $t('pakistan')},
	{value: "Palau", label: $t('palau')},
	{value: "Palestinian Territory", label: $t('palestinianTerritory')},
	{value: "Panama", label: $t('panama')},
	{value: "Papua New Guinea", label: $t('papuaNewGuinea')},
	{value: "Paraguay", label: $t('paraguay')},
	{value: "Peru", label: $t('peru')},
	{value: "Philippines", label: $t('philippines')},
	{value: "Pitcairn", label: $t('pitcairn')},
	{value: "Poland", label: $t('poland')},
	{value: "Portugal", label: $t('portugal')},
	{value: "Puerto Rico", label: $t('puertoRico')},
	{value: "Qatar", label: $t('qatar')},
	{value: "Reunion", label: $t('reunion')},
	{value: "Romania", label: $t('romania')},
	{value: "Russian Federation", label: $t('russianFederation')},
	{value: "RWANDA", label: $t('rwanda')},
	{value: "Saint Helena", label: $t('saintHelena')},
	{value: "Saint Kitts and Nevis", label: $t('saintKittsAndNevis')},
	{value: "Saint Lucia", label: $t('saintLucia')},
	{value: "Saint Pierre and Miquelon", label: $t('saintPierreAndMiquelon')},
	{value: "Saint Vincent and the Grenadines", label: $t('saintVincentAndTheGrenadines')},
	{value: "Samoa", label: $t('samoa')},
	{value: "San Marino", label: $t('sanMarino')},
	{value: "Sao Tome and Principe", label: $t('saoTomeAndPrincipe')},
	{value: "Saudi Arabia", label: $t('saudiArabia')},
	{value: "Senegal", label: $t('senegal')},
	{value: "Serbia and Montenegro", label: $t('serbiaAndMontenegro')},
	{value: "Seychelles", label: $t('seychelles')},
	{value: "Sierra Leone", label: $t('sierraLeone')},
	{value: "Singapore", label: $t('singapore')},
	{value: "Slovakia", label: $t('slovakia')},
	{value: "Slovenia", label: $t('slovenia')},
	{value: "Solomon Islands", label: $t('solomonIslands')},
	{value: "Somalia", label: $t('somalia')},
	{value: "South Africa", label: $t('southAfrica')},
	{value: "South Georgia and the South Sandwich Islands", label: $t('southGeorgiaAndTheSouthSandwichIslands')},
	{value: "Spain", label: $t('spain')},
	{value: "Sri Lanka", label: $t('sriLanka')},
	{value: "Sudan", label: $t('sudan')},
	{value: "Suriname", label: $t('suriname')},
	{value: "Svalbard and Jan Mayen", label: $t('svalbardAndJanMayen')},
	{value: "Swaziland", label: $t('swaziland')},
	{value: "Sweden", label: $t('sweden')},
	{value: "Switzerland", label: $t('switzerland')},
	{value: "Syrian Arab Republic", label: $t('syrianArabRepublic')},
	{value: "Taiwan", label: $t('taiwan')},
	{value: "Tajikistan", label: $t('tajikistan')},
	{value: "Tanzania", label: $t('tanzania')},
	{value: "Thailand", label: $t('thailand')},
	{value: "Timor-Leste", label: $t('timorLeste')},
	{value: "Togo", label: $t('togo')},
	{value: "Tokelau", label: $t('tokelau')},
	{value: "Tonga", label: $t('tonga')},
	{value: "Trinidad and Tobago", label: $t('trinidadAndTobago')},
	{value: "Tunisia", label: $t('tunisia')},
	{value: "Turkey", label: $t('turkey')},
	{value: "Turkmenistan", label: $t('turkmenistan')},
	{value: "Turks and Caicos Islands", label: $t('turksAndCaicosIslands')},
	{value: "Tuvalu", label: $t('tuvalu')},
	{value: "Uganda", label: $t('uganda')},
	{value: "Ukraine", label: $t('ukraine')},
	{value: "United Arab Emirates", label: $t('unitedArabEmirates')},
	{value: "United Kingdom", label: $t('unitedKingdom')},
	{value: "United States", label: $t('unitedStates')},
	{value: "United States Minor Outlying Islands", label: $t('unitedStatesMinorOutlyingIslands')},
	{value: "Uruguay", label: $t('uruguay')},
	{value: "Uzbekistan", label: $t('uzbekistan')},
	{value: "Vanuatu", label: $t('vanuatu')},
	{value: "Venezuela", label: $t('venezuela')},
	{value: "Viet Nam", label: $t('vietNam')},
	{value: "Virgin Islands", label: $t('virginIslands')},
	{value: "Virgin Islands", label: $t('virginIslands')},
	{value: "Wallis and Futuna", label: $t('wallisAndFutuna')},
	{value: "Western Sahara", label: $t('westernSahara')},
	{value: "Yemen", label: $t('yemen')},
	{value: "Zambia", label: $t('zambia')},
	{value: "Zimbabwe", label: $t('zimbabwe')}
    ],
	banque: [    
{value: "AL AKHDAR BANK", label: $t('alAkhdarBank')},
	{value: "AL BARID BANK", label: $t('alBaridBank')},
	{value: "ARAB BANK", label: $t('arabBank')},
	{value: "ATTIJARIWAFA BANK", label: $t('attijariwafaBank')},
	{value: "BANK AL YOUSR", label: $t('bankAlYousr')},
	{value: "BANK ASSAFA", label: $t('bankAssafa')},
	{value: "BANK OF AFRICA", label: $t('bankOfAfrica')},
	{value: "BANQUE CENTRALE POPULAIRE", label: $t('banqueCentralePopulaire')},
	{value: "BMCI", label: $t('bmci')},
	{value: "BTI BANK", label: $t('btiBank')},
	{value: "CDG CAPITAL", label: $t('cdgCapital')},
	{value: "CFG BANK", label: $t('cfgBank')},
	{value: "CIH BANK", label: $t('cihBank')},
	{value: "CITIBANK MAGHREB", label: $t('citibankMaghreb')},
	{value: "CREDIT AGRICOLE DU MAROC", label: $t('creditAgricoleDuMaroc')},
	{value: "CREDIT DU MAROC", label: $t('creditDuMaroc')},
	{value: "DAR EL AMANE", label: $t('darElAmane')},
	{value: "SOCIÉTÉ GÉNÉRALE MAROC", label: $t('socitGnraleMaroc')},
	{value: "UMNIA BANK", label: $t('umniaBank')},
	{value: "Encaissement sur Place", label: $t('encaissementSurPlace')}
    ],
	accesHandicape: [    
{value: "1", label: $t('true')},
	{value: "0", label: $t('false')}
    ],
	sourceDecouverte: [    
{value: "Université/Ecole", label: $t('universitEcole')},
	{value: "Supports commerciaux (dépliants, affiches)", label: $t('supportsCommerciauxDpliantsAffiches')},
	{value: "Bouche à oreille", label: $t('boucheOreille')},
	{value: "Annonce presse", label: $t('annoncePresse')},
	{value: "Tractage", label: $t('tractage')},
	{value: "Internet", label: $t('internet')},
	{value: "Publicité sur résidence", label: $t('publicitSurRsidence')},
	{value: "Autres", label: $t('autres')}
    ],
	civilite: [    
{value: "Monsieur", label: $t('monsieur')},
	{value: "Madame", label: $t('madame')},
	{value: "Mademoiselle", label: $t('mademoiselle')}
    ],
	banque2: [{"label":$t('alAkhdarBank'),"value":"AL AKHDAR BANK"},{"label":$t('alBaridBank'),"value":"AL BARID BANK"},{"label":$t('arabBank'),"value":"ARAB BANK"},{"label":$t('attijariwafaBank'),"value":"ATTIJARIWAFA BANK"},{"label":$t('bankAlYousr'),"value":"BANK AL YOUSR"},{"label":$t('bankAssafa'),"value":"BANK ASSAFA"},{"label":$t('bankOfAfrica'),"value":"BANK OF AFRICA"},{"label":$t('banqueCentralePopulaire'),"value":"BANQUE CENTRALE POPULAIRE"},{"label":$t('bmci'),"value":"BMCI"},{"label":$t('btiBank'),"value":"BTI BANK"},{"label":$t('cdgCapital'),"value":"CDG CAPITAL"},{"label":$t('cfgBank'),"value":"CFG BANK"},{"label":$t('cihBank'),"value":"CIH BANK"},{"label":$t('citibankMaghreb'),"value":"CITIBANK MAGHREB"},{"label":$t('creditAgricoleDuMaroc'),"value":"CREDIT AGRICOLE DU MAROC"},{"label":$t('creditDuMaroc'),"value":"CREDIT DU MAROC"},{"label":$t('darElAmane'),"value":"DAR EL AMANE"},{"label":$t('socitGnraleMaroc'),"value":"SOCIÉTÉ GÉNÉRALE MAROC"},{"label":$t('umniaBank'),"value":"UMNIA BANK"},{"label":$t('encaissementSurPlace'),"value":"Encaissement sur Place"}],
        exportFormats: {
            print: {
                label: 'Print',
                icon: 'pi pi-print',
                type: 'print',
                ext: '',
            },
            pdf: {
                label: 'Pdf',
                icon: 'pi pi-file-pdf',
                type: 'pdf',
                ext: 'pdf',
            },
            excel: {
                label: 'Excel',
                icon: 'pi pi-file-excel',
                type: 'excel',
                ext: 'xlsx',
            },
            csv: {
                label: 'Csv',
                icon: 'pi pi-table',
                type: 'csv',
                ext: 'csv',
            },
        },
        locales: {
  "fr": "French",
  "ru": "Russian",
  "zh-CN": "Chinese",
  "en-US": "English",
  "it": "Italian",
  "hi": "Hindi",
  "pt": "Portuguese",
  "de": "German",
  "es": "Spanish",
  "ar": "Arabic"
}
    }
}